---
apiVersion: v1
kind: Secret
metadata:
  name: chartrepo-secret
  namespace: default
stringData:
  password: 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
  username: anishpsoman

