apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dt-dt3-pong-4miape8fq-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: asoman
      nsId: 59df6695-396e-4215-95b4-34640569cb56
    image:
      imagePullSecrets: []
      pullPolicy: IfNotPresent
      repository: rt.cloud.dzsi.local/docker/rw.pong
      tag: '2005'
    macvlanNetName: dtdt3macvlanlinkprofile
    macvlanNetNamespace: asoman
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    service:
      type: NodePort
