apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-5g--ping-3bmumsues-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 0878cedb-4783-4bd2-9c0c-149b3f2babbb
    macvlanNetName: default5gcampusgoodmacvlanlinkprofile
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: '1'
    service:
      type: NodePort
