apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-t1-ping-urp4kcuo9-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: asoman
      nsId: 8d99ae14-09c9-4bb7-8495-f238705b40bf
    image:
      imagePullSecrets: []
      pullPolicy: IfNotPresent
      repository: artifactory.riftio.com/docker/rw.ping
      tag: '2004'
    macvlanNetName: defaultt1macvlanlinkprofile
    macvlanNetNamespace: asoman
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: 1
    service:
      type: NodePort
