apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-an1-pong-s9janor8y-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: asoman
      nsId: 34d22f8b-5913-4d5d-a4e1-c91c8abd5250
    image:
      imagePullSecrets: []
      pullPolicy: IfNotPresent
      repository: artifactory.riftio.com/docker/rw.pong
      tag: '2005'
    macvlanNetName: defaultan1macvlanlinkprofile
    macvlanNetNamespace: asoman
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    service:
      type: LoadBalancer
