apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dt-dt3-ping-mejrxsmj1-0-0-0
  namespace: default
spec:
  chart:
    spec:
      chart: ./fluxdc/dt33/dt-dt3-ping-mejrxsmj1-0-0-0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: chartrepo
        namespace: default
  interval: 5m0s
  postRenderers:
  - kustomize:
      patches:
      - patch: "\napiVersion: apps/v1\nkind: (Deployment|ReplicaSet|StatefulSet|DaemonSet)\n\
          metadata:\n  name: will-be-ingored\nspec:\n  template:\n    metadata:\n\
          \      annotations:\n        dzsi.com/dzsx-network-function-href: https://10.157.102.68:8008/tmf-api/mano/serviceInventory/v4/dt/service/service:DZSXNetworkFunction:dt:3eebcd24-2860-4157-9736-788c1c070333\n\
          \        dzsi.com/dzsx-network-function-id: service:DZSXNetworkFunction:dt:3eebcd24-2860-4157-9736-788c1c070333\n"
        target:
          kind: (Deployment|ReplicaSet|StatefulSet|DaemonSet)
  releaseName: dt-dt3-ping-mejrxsmj1-0-0-0
  targetNamespace: default
  values: {}
