apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dt-dt3-ping-mejrxsmj1-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: asoman
      nsId: 014e7c09-193b-40dd-94de-a8cd2673e621
    image:
      imagePullSecrets: []
      pullPolicy: IfNotPresent
      repository: rt.cloud.dzsi.local/docker/rw.ping
      tag: '2004'
    macvlanNetName: dtdt33macvlanlinkprofile
    macvlanNetNamespace: asoman
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: 1
    service:
      type: NodePort
