apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-an1-ping-sqke0jztk-0-0-0
  namespace: default
spec:
  chart:
    spec:
      chart: ./fluxdc/An1/de-an1-ping-sqke0jztk-0-0-0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: chartrepo
        namespace: default
  interval: 5m0s
  postRenderers:
  - kustomize:
      patches:
      - patch: "\n- op: add\n  path: /spec/template/metadata/annotations/dzsi.com~1dzsx-network-function-id\n\
          \  value: service:DZSXNetworkFunction:default:c87b85e4-b044-4afb-bfa7-2c4b097078d6\n\
          - op: add\n  path: /spec/template/metadata/annotations/dzsi.com~1dzsx-network-function-href\n\
          \  value: https://10.157.107.67:8008/tmf-api/mano/serviceInventory/v4/default/service/service:DZSXNetworkFunction:default:c87b85e4-b044-4afb-bfa7-2c4b097078d6\n"
        target:
          kind: (Deployment|ReplicaSet|StatefulSet|DaemonSet)
  releaseName: de-an1-ping-sqke0jztk-0-0-0
  targetNamespace: default
  values: {}
