apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-tes-ping-hnxusdcvl-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: asoman
      nsId: a628c8b9-f7c8-4991-806d-be693e37a553
    image:
      imagePullSecrets: []
      pullPolicy: IfNotPresent
      repository: artifactory.riftio.com/docker/rw.ping
      tag: '2004'
    macvlanNetName: defaulttestsrv1macvlanlinkprofile
    macvlanNetNamespace: asoman
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: 1
    service:
      type: NodePort
