apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fl-5g--pong-nmqup35ad-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: c0ddf244-bd3e-44c9-97a3-4609c4aa9bc5
    macvlanNetName: flux5gcampusgoodmacvlanlinkprofile
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    replicaCount: '1'
    service:
      type: LoadBalancer
