apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fl-5g--pong-nmqup35ad-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: 623890c4-0e37-4417-bbe9-5e8486151729
    macvlanNetName: flux5gcampusgoodmacvlanlinkprofile
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    replicaCount: '1'
    service:
      type: LoadBalancer
