apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-pp1-pong-7kcid9rpm-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: asoman
      nsId: 62de7c21-9273-4f5d-b8c8-1c3c0f563252
    image:
      imagePullSecrets: []
      pullPolicy: IfNotPresent
      repository: artifactory.riftio.com/docker/rw.pong
      tag: '2005'
    macvlanNetName: defaultpp1macvlanlinkprofile
    macvlanNetNamespace: asoman
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    service:
      type: LoadBalancer
