apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fl-5g--ping-jvh0ikoxj-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: default
      nsId: c0ddf244-bd3e-44c9-97a3-4609c4aa9bc5
    macvlanNetName: flux5gcampusgoodmacvlanlinkprofile
    macvlanNetNamespace: default
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: '1'
    service:
      type: NodePort
