apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dt-dt1-ping-etfatdiv1-0-0-0
  namespace: default
spec:
  values:
    global:
      namespace: asoman
      nsId: a97cb696-5fe4-46c3-a6ed-7540e3060a28
    image:
      imagePullSecrets: []
      pullPolicy: IfNotPresent
      repository: rt.cloud.dzsi.local/docker/rw.ping
      tag: '2004'
    macvlanNetName: dtdt11macvlanlinkprofile
    macvlanNetNamespace: asoman
    metrics:
      annotations:
        path: /api/v1/ping/metrics
        port: 18888
        scrape: true
      enabled: true
    replicaCount: 1
    service:
      type: NodePort
