apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: de-tes-pong-s5qcqqat6-0-0-1
  namespace: default
spec:
  values:
    global:
      namespace: asoman
      nsId: a628c8b9-f7c8-4991-806d-be693e37a553
    image:
      imagePullSecrets: []
      pullPolicy: IfNotPresent
      repository: artifactory.riftio.com/docker/rw.pong
      tag: '2005'
    macvlanNetName: defaulttestsrv1macvlanlinkprofile
    macvlanNetNamespace: asoman
    metrics:
      annotations:
        path: /api/v1/pong/metrics
        port: 18889
        scrape: true
      enabled: true
    nodeSelector: {}
    service:
      type: LoadBalancer
