---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: chartrepo
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: chartrepo-secret
  url: https://github.com/anishpsoman/chartrepo.git
